import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "VITALITEA-ENERGY-SUPPORT",
    name: "Vitalitea: Anti-Inflammatory & Energy Support",
    botanicalName: "Zingiber officinale, Hibiscus sabdariffa, Rosmarinus officinalis & Panax ginseng",
    subtitle: "Organic Caffeine-Free Energy, Cellular Revival & Anti-Inflammatory Blend",
    description: "Crafted in our apothecary with pure whole-plant botanicals, Vitalitea delivers sustained, clean vitality without nervous system jitter or afternoon crashes. Rich in bioactive gingerols and crimson hibiscus polyphenols to extinguish systemic inflammation while Korean ginseng and aromatic rosemary restore stamina, clarity, and sovereign womb vitality.\n\nHot & Cold Infusion | 100% Organic | Caffeine Free",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Immunity",
    image: "/vitaaaaality_1.png",
    gallery: ["/vitaaaaality_1.png"],
    volume: "10 oz Pouch or 20 oz Pack",
    sizeOptions: ["10 oz Pouch", "20 oz Pack"],
    sizePrices: {
      "10 oz Pouch": 14.99,
      "20 oz Pack": 24.99,
      "10 oz": 14.99,
      "20 oz": 24.99
    },
    sizeCompareAtPrices: {
      "10 oz Pouch": 17.24,
      "20 oz Pack": 29.99,
      "10 oz": 17.24,
      "20 oz": 29.99
    },
    inStock: true,
    featured: true,
    rating: 4.98,
    reviewCount: 48,
    ingredients: ["Organic Ginger Root (Zingiber officinale)", "Organic Hibiscus Petals (Hibiscus sabdariffa)", "Wildcrafted Rosemary Leaf (Rosmarinus officinalis)", "Organic Red Ginseng Root (Panax ginseng)"],
    ritualGuide: "Steep 1 tablespoon in 10–12 oz of boiling spring water for 10–15 minutes covered to preserve aromatic volatile oils. Enjoy piping hot with raw honey or chill over ice with fresh citrus slices for an invigorating midday revival.",
    dosage: "1 to 2 cups daily for sustained cellular stamina and anti-inflammatory balance",
    scentNotes: "Spicy ginger warmth, tart hibiscus blossom, crisp piney rosemary, earthy ginseng undertones",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Immunity", "Energy", "Anti-Inflammatory", "Haus of Zen", "Featured"]
  },
  {
    id: "IO7D3X3TYCUK7DGX2OV4YQAG",
    squareCatalogItemId: "IO7D3X3TYCUK7DGX2OV4YQAG",
    squareVariationId: "FIPHPT6ARUOQTTZZA2OJCQ7T",
    name: "Herbal Detox Tea",
    botanicalName: "Arctium lappa, Taraxacum officinale, Urtica dioica & Rosmarinus officinalis",
    subtitle: "Daily Detox Cleanse • Caffeine-Free Whole-Plant Botanical Blend",
    description: "Herbal Detox features a synergistic blend of whole-plant botanicals formulated to support your body's natural daily cleansing pathways, liver harmony, and cellular refresh.\n\nIngredients: Burdock · Dandelion Leaf · Dandelion Root · Nettle · Rosemary\n\n100% Organic · Caffeine Free · Hot & Cold Infusion",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Immunity",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/fb70a53546804c6aa8352fbb5ca06592cc01ac82/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/fb70a53546804c6aa8352fbb5ca06592cc01ac82/original.png"],
    volume: "10 oz / 283.4g Botanical Pouch",
    sizeOptions: undefined,
    inStock: true,
    featured: true,
    rating: 4.92,
    reviewCount: 22,
    ingredients: ["Organic Burdock Root", "Organic Dandelion Leaf", "Organic Dandelion Root", "Organic Stinging Nettle", "Organic Rosemary"],
    ritualGuide: "Steep 1–2 teaspoons in 8–10 oz of boiling spring water for 10–12 minutes. Can also be prepared as a chilled cold brew overnight.",
    dosage: "1 to 2 nourishing cups daily",
    scentNotes: "Deep earthy root warmth, fresh verdant dandelion, pine-herbal rosemary",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Immunity", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "FUEYES7TGPYWEQ4L5CE2NKUS",
    squareCatalogItemId: "FUEYES7TGPYWEQ4L5CE2NKUS",
    squareVariationId: "7DZKRUXFHNEEGQ25KP2JJCXD",
    name: "Rise & Shine Tea",
    botanicalName: "Withania somnifera, Rhodiola rosea & Ocimum sanctum",
    subtitle: "Anxiety & Depression Relief • Adaptogenic Nervous System Harmony",
    description: "Rise & Shine is crafted to promote relief from anxiety and depression while restoring emotional resilience, calming an overworked nervous system, and uplifting morning equilibrium.\n\nIngredients: Ashwagandha · Rhodiola · Holy Basil\n\n100% Organic · Caffeine Free · Hot & Cold Infusion",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Clarity",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/d467919772cf660ab5a51088c231e32da33e1650/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/d467919772cf660ab5a51088c231e32da33e1650/original.png"],
    volume: "10 oz / 283.4g Botanical Pouch",
    sizeOptions: undefined,
    inStock: true,
    featured: true,
    rating: 4.93,
    reviewCount: 25,
    ingredients: ["Organic Ashwagandha Root", "Organic Rhodiola Rosea", "Organic Holy Basil (Tulsi)"],
    ritualGuide: "Steep 1 tablespoon in freshly boiled water for 8–10 minutes. Inhale the bright aromatic steam before your first mindful morning sip.",
    dosage: "1 cup in the morning or early afternoon",
    scentNotes: "Warm adaptogenic earth, uplifting sweet tulsi, soothing botanical finish",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Clarity", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "FGAQ42HO546QP4DQW5K2KRFA",
    squareCatalogItemId: "FGAQ42HO546QP4DQW5K2KRFA",
    squareVariationId: "B4YWEMTPIM4ZO3Z6BNNMP2IX",
    name: "Pure Gold Infusion Tea",
    botanicalName: "Crocus sativus, Curcuma longa & Zingiber officinale",
    subtitle: "Anti-Inflammatory Support • Sacred Saffron, Golden Turmeric & Warming Ginger",
    description: "Pure Gold Infusion pairs sovereign saffron threads with deeply anti-inflammatory turmeric rhizome and warming ginger to calm systemic inflammation, support joint ease, and promote vibrant vitality in every golden sip.\n\nIngredients: Saffron · Turmeric · Ginger\n\n100% Organic · Caffeine Free · Hot & Cold Infusion",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Immunity",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/e011a9e1d8122b77032dcc8960dcbfe9bee517f7/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/e011a9e1d8122b77032dcc8960dcbfe9bee517f7/original.png"],
    volume: "10 oz / 283.4g Botanical Pouch",
    sizeOptions: undefined,
    inStock: true,
    featured: true,
    rating: 4.94,
    reviewCount: 28,
    ingredients: ["Pure Organic Saffron Threads", "Organic Turmeric Rhizome", "Organic Ginger Root"],
    ritualGuide: "Simmer in boiling spring water or gentle oat milk for 10 minutes. Whisk with raw honey or agave for golden botanical comfort.",
    dosage: "Enjoy daily as a soothing golden restorative",
    scentNotes: "Exotic floral saffron aroma, warm golden turmeric, spicy ginger",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Immunity", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "JNE6KL5CSPUVLUI44SIXV4O6",
    squareCatalogItemId: "JNE6KL5CSPUVLUI44SIXV4O6",
    squareVariationId: "4PNBDB464J45R3X7LULFCDZY",
    name: "Night Nectar Tea",
    botanicalName: "Lavandula angustifolia, Valeriana officinalis, Avena sativa & Melissa officinalis",
    subtitle: "Sleep Support • Restful Evening Nervous System Tonic",
    description: "Night Nectar features a relaxing blend of sleep-supportive botanicals designed to ease insomnia and calm mental chatter for deeply restorative, tranquil sleep.\n\nIngredients: Lavender · Valerian Root · Oat Straw · Lemon Balm\n\n100% Organic · Caffeine Free · Hot & Cold Infusion",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Sleep",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/205ad1eed4c343bb1b52200a640fe996b14cb2a6/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/205ad1eed4c343bb1b52200a640fe996b14cb2a6/original.png"],
    volume: "10 oz / 283.4g Botanical Pouch",
    sizeOptions: undefined,
    inStock: true,
    featured: true,
    rating: 4.95,
    reviewCount: 31,
    ingredients: ["Organic Lavender Blossoms", "Organic Valerian Root", "Organic Milky Oat Straw", "Organic Lemon Balm"],
    ritualGuide: "Infuse 1–2 tablespoons in hot water 30–45 minutes before sleep. Keep covered to trap the calming essential oils.",
    dosage: "1 warm cup in your evening winding-down ritual",
    scentNotes: "Sweet floral lavender, calming lemon balm citrus, mellow rustic oatstraw",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Sleep", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "ASMEWGCDVF2BFXBTRT2AUPIL",
    squareCatalogItemId: "ASMEWGCDVF2BFXBTRT2AUPIL",
    squareVariationId: "KQIJU7ULMELISRDJHCVM2FT3",
    name: "Energy Elixir Tea",
    botanicalName: "Rosmarinus officinalis, Urtica dioica & Ocimum sanctum",
    subtitle: "Coffee Replacement • Caffeine-Free Cellular Energy & Brain Focus",
    description: "Energy Elixir Tea is a revitalizing caffeine-free blend designed to replace your morning coffee, featuring whole botanicals that boost energy, reduce brain fog, and support cellular vitality without jitters or afternoon crashes.\n\nIngredients: Rosemary · Nettle · Holy Basil\n\n100% Organic · Caffeine Free · Hot & Cold Infusion",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Clarity",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/c8585f139217d14e64d0f2f6ad612aecb63be85d/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/c8585f139217d14e64d0f2f6ad612aecb63be85d/original.png"],
    volume: "10 oz / 283.4g Botanical Pouch",
    sizeOptions: undefined,
    inStock: true,
    featured: true,
    rating: 4.96,
    reviewCount: 34,
    ingredients: ["Organic Rosemary Leaf", "Organic Stinging Nettle Leaf", "Organic Holy Basil (Tulsi)"],
    ritualGuide: "Steep 1 tablespoon in freshly boiled water for 8–10 minutes for sustained clean focus and vitality.",
    dosage: "1 to 2 cups to kickstart morning focus and energy",
    scentNotes: "Invigorating pine rosemary, rich verdant mineral nettle, aromatic holy basil",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Clarity", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "HT4PPMHFPELV7FNDKN3J5WD6",
    squareCatalogItemId: "HT4PPMHFPELV7FNDKN3J5WD6",
    squareVariationId: "WO5JIGT4QQOX2FY3AXJ4QDNX",
    name: "Menstrual Relief Tea",
    botanicalName: "Achillea millefolium, Arctium lappa, Zingiber officinale, Withania somnifera, Urtica dioica, Matricaria chamomilla & Actaea racemosa",
    subtitle: "Heavy Flow & Cramps Support • Uterine Muscle & Pelvic Comfort",
    description: "Formulated specifically for heavy flow and menstrual cramp support. A targeted botanical blend crafted to ease spasms, nourish pelvic blood flow, and bring soothing comfort throughout your cycle.\n\nIngredients: Yarrow Flowers · Burdock · Ginger · Ashwagandha · Nettle · Chamomile · Black Cohosh\n\n100% Organic · Caffeine Free · Hot & Cold Infusion",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Herbal Tea Blends",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/42023337cf6f3b260429da381ff325840f1373f3/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/42023337cf6f3b260429da381ff325840f1373f3/original.png"],
    volume: "10 oz / 283.4g Botanical Pouch",
    sizeOptions: undefined,
    inStock: true,
    featured: true,
    rating: 4.97,
    reviewCount: 37,
    ingredients: ["Organic Yarrow Flowers", "Organic Burdock Root", "Organic Ginger Root", "Organic Ashwagandha", "Organic Stinging Nettle", "Organic Chamomile", "Organic Black Cohosh"],
    ritualGuide: "Brew strong: steep 2 tablespoons covered in 10 oz boiling water for 15 minutes. Sip hot with a heating pad over your pelvis.",
    dosage: "2 to 3 cups during premenstrual and bleed days",
    scentNotes: "Aromatic herbal yarrow, comforting chamomile, warming ginger and earthy roots",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Herbal Tea Blends", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "7WY5XTF5FPSF2OUOVBC6G7UV",
    squareCatalogItemId: "7WY5XTF5FPSF2OUOVBC6G7UV",
    squareVariationId: "EWKTQQYXHGN7UFK3HLSVKXE2",
    name: "Purple Passion Cold Tea Infusion",
    botanicalName: "Clitoria ternatea, Lavandula angustifolia, Melissa officinalis & Citrus limon",
    subtitle: "Botanical Butterfly Pea, Lavender & Citrus Cold Infusion",
    description: "A vibrant, naturally refreshing cold tea infusion crafted with lavender, butterfly pea flower, lemon balm, and fresh lemon. Naturally purple and made with 100% organic ingredients for slow afternoons, warm days, and everyday moments of calm.\n\nIngredients: Lavender · Butterfly Pea Flower · Lemon Balm · Lemon\n\n100% Organic · Naturally Sweetened · Caffeine Free",
    price: 9.99,
    compareAtPrice: undefined,
    category: "Herbal Cold Tea Infusions",
    intent: "Calm",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/c7443d054298977e85b81ebea8ae44bdbcc71f06/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/c7443d054298977e85b81ebea8ae44bdbcc71f06/original.jpeg"],
    volume: "16 fl oz / 479 mL Glass Bottle",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.98,
    reviewCount: 40,
    ingredients: ["Organic Lavender Blossoms", "Organic Butterfly Pea Flower", "Organic Lemon Balm", "Organic Fresh Lemon Juice", "Pure Mountain Spring Water"],
    ritualGuide: "Enjoy chilled over ice. Naturally turns from royal indigo to amethyst violet when squeezed with fresh citrus.",
    dosage: "Sip freely throughout afternoons for refreshing calm",
    scentNotes: "French lavender, bright citrus peel, cooling herbal sweetness",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Naturally Sweetened', 'Caffeine Free', 'Non-GMO'],
    tags: ["Herbal Cold Tea Infusions", "Calm", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "QGZ6PVFYJ7CZ7HHW45CFKR72",
    squareCatalogItemId: "QGZ6PVFYJ7CZ7HHW45CFKR72",
    squareVariationId: "ELQEN2UZFWHXA3G5OSZDKZV3",
    name: "Sunrise Cold Tea Infusion",
    botanicalName: "Hibiscus sabdariffa, Zingiber officinale, Withania somnifera, Rosmarinus officinalis, Urtica dioica, Matricaria chamomilla & Avena sativa",
    subtitle: "Vibrant Hibiscus, Ashwagandha & Ginger Adaptogenic Cold Brew",
    description: "A vibrant herbal cold tea infusion crafted to awaken the senses with tart hibiscus, warming ginger, adaptogenic ashwagandha, rosemary, mineral nettle, chamomile, and soothing oatstraw.\n\nIngredients: Hibiscus · Ginger · Ashwagandha · Rosemary · Nettle · Chamomile · Oatstraw\n\n100% Organic · Naturally Sweetened · Caffeine Free",
    price: 9.99,
    compareAtPrice: undefined,
    category: "Herbal Cold Tea Infusions",
    intent: "Radiance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/fab08e18b430d6880c98a6f47fb49338f43bcf67/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/fab08e18b430d6880c98a6f47fb49338f43bcf67/original.jpeg"],
    volume: "16 fl oz Ready-to-Drink Bottle",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.99,
    reviewCount: 43,
    ingredients: ["Organic Crimson Hibiscus", "Organic Ginger Root", "Organic Ashwagandha", "Organic Rosemary Leaf", "Organic Stinging Nettle", "Organic Chamomile", "Organic Oatstraw", "Pure Mountain Spring Water"],
    ritualGuide: "Serve chilled over stone ice cubes. A tart, vibrant tonic packed with antioxidants and adaptogenic minerals.",
    dosage: "Enjoy chilled in the morning or post-movement",
    scentNotes: "Bold tart berry, warm ginger spice, botanical pine rosemary",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Naturally Sweetened', 'Caffeine Free', 'Non-GMO'],
    tags: ["Herbal Cold Tea Infusions", "Radiance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "HJ5J2PYI3QOAAB4ZUWSVILC2",
    squareCatalogItemId: "HJ5J2PYI3QOAAB4ZUWSVILC2",
    squareVariationId: "ZBX7KFZ6EQX6YV54QSZQNYJA",
    name: "Nature's Lemonade",
    botanicalName: "Citrus limon & Agave tequilana",
    subtitle: "100% Organic Fresh Lemons & Organic Raw Agave Elixir",
    description: "Pure, refreshing, and naturally vibrant. Our all-natural lemonade is made with real lemons and sweetened with 100% organic agave for a smooth, naturally sweet finish.\n\nIngredients: Real Lemon · 100% Organic Agave · Spring Water\n\nAll Natural · Real Ingredients · Refreshingly Simple",
    price: 8.99,
    compareAtPrice: undefined,
    category: "Herbal Cold Tea Infusions",
    intent: "Radiance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/fd76c9a6b863b833aca687b2c011af08a20e2183/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/fd76c9a6b863b833aca687b2c011af08a20e2183/original.jpeg"],
    volume: "16 fl oz Ready-to-Drink Bottle",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.92,
    reviewCount: 46,
    ingredients: ["100% Organic Fresh-Squeezed Lemons", "100% Organic Raw Blue Agave Nectar", "Pure Mountain Spring Water"],
    ritualGuide: "Shake well and enjoy ice-cold for pure electrolyte hydration and bright sunshine vitality.",
    dosage: "Refreshing everyday hydration",
    scentNotes: "Freshly squeezed Meyer lemon zest, sweet organic agave nectar",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Naturally Sweetened', 'Caffeine Free', 'Non-GMO'],
    tags: ["Herbal Cold Tea Infusions", "Radiance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "TFAII2LGXG7XLHZHNPG6O75Y",
    squareCatalogItemId: "TFAII2LGXG7XLHZHNPG6O75Y",
    squareVariationId: "XTBLUF4HMYUGUA4J6FTU6GUJ",
    name: "tea time",
    botanicalName: "Herbal Tea Sample & Tasting Selection",
    subtitle: "Apothecary Tasting & Sample Cup",
    description: "An authentic tasting portion of our handcrafted botanical herbal infusions. Perfect for discovering your favorite blend or savoring a mindful tea ritual moment.",
    price: 1.00,
    compareAtPrice: undefined,
    category: "Herbal Tea Blends",
    intent: "Calm",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/5f765455b2f8e981d8653559a309ea06d5cb8ca3/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/5f765455b2f8e981d8653559a309ea06d5cb8ca3/original.jpeg"],
    volume: "Sample Cup / Single Serving",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 5.0,
    reviewCount: 15,
    ingredients: ["Select Organic Botanicals", "Spring Water"],
    ritualGuide: "Enjoy warm and savor slowly.",
    dosage: "1 tasting cup",
    scentNotes: "Fresh botanical aromatics",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO'],
    tags: ["Herbal Tea Blends", "Calm", "Sample", "Haus of Zen"]
  },
  {
    id: "MLGMLJPR3TCL6UCBUWDSP54W",
    squareCatalogItemId: "MLGMLJPR3TCL6UCBUWDSP54W",
    squareVariationId: "JUJWPHIG7XC7OO3WV7MOQ7TQ",
    name: "Zen Womb Yoni Blend",
    botanicalName: "Rosmarinus officinalis, Mentha piperita, Rubus idaeus, Zingiber officinale, Lavandula angustifolia & Withania somnifera",
    subtitle: "Refresh & Tighten • Balance Vaginal pH, Disinfect Uterus & Revitalize Womb",
    description: "Formulated to refresh and tighten pelvic tissues, balance vaginal pH, disinfect the uterine environment, and revitalize natural womb vitality.\n\nIngredients: Rosemary · Peppermint · Red Raspberry Leaf · Ginger · Lavender · Ashwagandha\n\n100% Handcrafted Organic Yoni Steam Blend",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Yoni Steaming",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/1293aefb9c731fa28f6fd33e0b464677d0b8e6d1/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/1293aefb9c731fa28f6fd33e0b464677d0b8e6d1/original.png"],
    volume: "8 oz / 226.8g Handcrafted Botanical Steam Blend",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.93,
    reviewCount: 49,
    ingredients: ["Organic Rosemary", "Organic Peppermint", "Organic Red Raspberry Leaf", "Organic Ginger Root", "Organic Lavender", "Organic Ashwagandha"],
    ritualGuide: "Add 1 cup of herbs to 2 quarts of simmering water. Allow to steam gently under a yoni stool or covered pelvic sanctuary for 15–20 minutes.",
    dosage: "1 to 2 ritual steams per cycle (not during active bleed or pregnancy)",
    scentNotes: "Crisp cooling peppermint, sacred rosemary, soothing lavender, warming ginger",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Yoni Steaming", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "CPRSYQEKNBO3CALP3ISPIEIN",
    squareCatalogItemId: "CPRSYQEKNBO3CALP3ISPIEIN",
    squareVariationId: "U4JUXQ5HA6ANB22JO7HXA66O",
    name: "Follicular Phase Yoni Blend",
    botanicalName: "Achillea millefolium, Arctium lappa, Zingiber officinale, Withania somnifera, Urtica dioica, Matricaria chamomilla & Actaea racemosa",
    subtitle: "Rebuild & Restore • Cyclical Follicular Phase Pelvic Steam",
    description: "Rebuild and restore your pelvic sanctuary post-bleed. A restorative botanical steam that supports uterine lining renewal, healthy follicular maturation, and renewed vitality.\n\nIngredients: Yarrow Flowers · Burdock · Ginger · Ashwagandha · Nettle · Chamomile · Black Cohosh\n\n100% Handcrafted Organic Yoni Steam Blend",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Yoni Steaming",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/8d180a9f6fca21807913d3fe279ed69b8911518a/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/8d180a9f6fca21807913d3fe279ed69b8911518a/original.png"],
    volume: "8 oz / 226.8g Handcrafted Botanical Steam Blend",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.94,
    reviewCount: 52,
    ingredients: ["Organic Yarrow Flowers", "Organic Burdock Root", "Organic Ginger", "Organic Ashwagandha", "Organic Stinging Nettle", "Organic Chamomile", "Organic Black Cohosh"],
    ritualGuide: "Steam gently following the end of your bleed through ovulation to encourage pelvic blood flow and uterine tissue regeneration.",
    dosage: "1 ritual steam during the follicular phase (days 5–12)",
    scentNotes: "Balancing yarrow blossom, rich earthy burdock root, calming chamomile",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Yoni Steaming", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "IY2ARUYW47DUR7DJVOZKDW7M",
    squareCatalogItemId: "IY2ARUYW47DUR7DJVOZKDW7M",
    squareVariationId: "6PVRCX5DXHJGHHDK3UM6TGWL",
    name: "Ovulation Phase Yoni Blend",
    botanicalName: "Rubus idaeus, Rosa damascena, Hibiscus sabdariffa, Trifolium pratense & Matricaria chamomilla",
    subtitle: "Open & Receive • Fertility, Sensuality & Emotional Openness Steam",
    description: "Open and receive during your peak ovulatory window. Nourishes cervical fluid, heightens sacral sensuality, supports fertile circulation, and cultivates emotional openness.\n\nIngredients: Red Raspberry Leaf · Rose · Hibiscus · Red Clover · Chamomile\n\n100% Handcrafted Organic Yoni Steam Blend",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Yoni Steaming",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/09c756b2e6184866869da0f33a907fbce9fb3fed/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/09c756b2e6184866869da0f33a907fbce9fb3fed/original.png"],
    volume: "8 oz / 226.8g Handcrafted Botanical Steam Blend",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.95,
    reviewCount: 55,
    ingredients: ["Organic Red Raspberry Leaf", "Organic Rose Petals", "Organic Hibiscus Flowers", "Organic Red Clover Blossoms", "Organic Chamomile Flowers"],
    ritualGuide: "Steamed gently at the mid-cycle window to open the sacral chakra and nourish pelvic circulation.",
    dosage: "1 gentle ritual steam around mid-cycle ovulation",
    scentNotes: "Intoxicating sweet rose petals, tart radiant hibiscus, gentle floral chamomile",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Yoni Steaming", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "LIP3SAT4KMZC3OYKPE5YV67O",
    squareCatalogItemId: "LIP3SAT4KMZC3OYKPE5YV67O",
    squareVariationId: "EVS5B7G3N5YWZRKVJG672STG",
    name: "Luteal Phase Yoni Blend",
    botanicalName: "Alchemilla vulgaris, Viburnum opulus, Matricaria chamomilla, Melissa officinalis & Vitex agnus-castus",
    subtitle: "Ground & Soothe • Progesterone Harmony & Premenstrual Ease",
    description: "Ground and soothe your pelvic sanctuary prior to menstruation. Formulated to support progesterone harmony, reduce pelvic tension, and provide grounded emotional peace.\n\nIngredients: Lady’s Mantle · Cramp Bark · Chamomile · Lemon Balm · Vitex Chaste Tree Berry\n\n100% Handcrafted Organic Yoni Steam Blend",
    price: 14.99,
    compareAtPrice: 17.24,
    category: "Yoni Steaming",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/195ede2e32ee608a3a654611f1bd0678b974c19e/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/195ede2e32ee608a3a654611f1bd0678b974c19e/original.png"],
    volume: "8 oz / 226.8g Handcrafted Botanical Steam Blend",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.96,
    reviewCount: 58,
    ingredients: ["Organic Lady’s Mantle", "Organic Cramp Bark", "Organic Chamomile", "Organic Lemon Balm", "Organic Vitex Chaste Tree Berry"],
    ritualGuide: "Prepared as a warm aromatic pelvic steam or gentle foot soak to ground progesterone rhythms and ease irritability before menses.",
    dosage: "1 gentle steam 5–7 days before expected bleed",
    scentNotes: "Calming chamomile flowers, comforting vanilla earth, soft mint",
    certifications: ['100% Handcrafted', '100% Certified Organic', 'Caffeine Free', 'Non-GMO', 'Ethically Sourced'],
    tags: ["Yoni Steaming", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "YNKALHARXULY2RKWN2YVS6GH",
    squareCatalogItemId: "YNKALHARXULY2RKWN2YVS6GH",
    squareVariationId: "LLQ5JISRN4BIJLCH3K6JAUTH",
    name: "Herbal Consultation - 30 Mins",
    botanicalName: "Clinical Herbalism & Assessment",
    subtitle: "Targeted Holistic Health, Hormonal & Lifestyle Mapping",
    description: "A focused, 30-minute one-on-one clinical herbalism consultation exploring your current health goals, hormonal balance, lifestyle rhythms, and bespoke botanical recommendations.",
    price: 49.99,
    compareAtPrice: 59.99,
    category: "Consultations & Rituals",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/5153dd84693a4698719f6bc71e20ea1133fcbb96/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/5153dd84693a4698719f6bc71e20ea1133fcbb96/original.jpeg"],
    volume: "30-Minute Consultation",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.98,
    reviewCount: 64,
    ingredients: ["Targeted Health Review", "Tongue & Pulse Assessment", "Custom Formulation Plan", "Follow-up Guide"],
    ritualGuide: "Focused clinical inquiry into your current bodily state, hormonal rhythms, nutritional baselines, and custom herbal support.",
    dosage: "30-minute private consultation",
    scentNotes: "Tranquil sanctuary atmosphere, herbal incense and singing bowls",
    certifications: ['100% Handcrafted', 'All-Natural Botanicals', 'Ethically Sourced', 'Non-GMO'],
    tags: ["Consultations & Rituals", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "RZ4IAS62WUTNBB2LEJXGPCSH",
    squareCatalogItemId: "RZ4IAS62WUTNBB2LEJXGPCSH",
    squareVariationId: "LJSYZGPCHP2ZUDXDHQ3F4SQJ",
    name: "Herbal Consultation - 60 mins",
    botanicalName: "Clinical Herbalism & Comprehensive Assessment",
    subtitle: "Comprehensive Holistic Health, Hormonal & Lifestyle Mapping",
    description: "An in-depth, 60-minute one-on-one clinical herbalism consultation thoroughly evaluating your health history, hormonal cycle, lifestyle patterns, and bespoke botanical formulations.",
    price: 59.99,
    compareAtPrice: 69.99,
    category: "Consultations & Rituals",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/5153dd84693a4698719f6bc71e20ea1133fcbb96/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/5153dd84693a4698719f6bc71e20ea1133fcbb96/original.jpeg"],
    volume: "60-Minute Consultation",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.99,
    reviewCount: 68,
    ingredients: ["Full Health Narrative Review", "Tongue & Pulse Assessment", "In-depth Custom Formulation Plan", "Written Follow-up Protocol"],
    ritualGuide: "Comprehensive clinical inquiry into your bodily rhythms, pelvic health, nutritional baselines, and custom herbal preparations.",
    dosage: "60-minute private consultation",
    scentNotes: "Tranquil sanctuary atmosphere, herbal incense and singing bowls",
    certifications: ['100% Handcrafted', 'All-Natural Botanicals', 'Ethically Sourced', 'Non-GMO'],
    tags: ["Consultations & Rituals", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "X5PUHPCTPHUZHCJW2LSVISKG",
    squareCatalogItemId: "X5PUHPCTPHUZHCJW2LSVISKG",
    squareVariationId: "NLH42OWEBLRN45Q546OAF2TV",
    name: "The Quick Audit",
    botanicalName: "Virtual Herbal Assessment",
    subtitle: "30-Minute Targeted Symptom Check & Custom Selection",
    description: "30 Minutes • Virtual\nNot sure where to begin? This focused session helps you identify the right tea and herbal support for your body right now, based on your current symptoms and goals.\nPersonalized symptom check in\nTargeted tea and product recommendation\nComplimentary $20 apothecary item included",
    price: 75.00,
    compareAtPrice: 85.00,
    category: "Consultations & Rituals",
    intent: "Clarity",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/0eb2eb56c73174e1ca9abff8890c49c60ac3fd1f/original.png",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/0eb2eb56c73174e1ca9abff8890c49c60ac3fd1f/original.png"],
    volume: "30-Min Virtual Session + $20 Credit",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.99,
    reviewCount: 67,
    ingredients: ["Personalized Symptom Check-in", "Targeted Tea Recommendation", "$20 Apothecary Credit Included"],
    ritualGuide: "Ideal for those seeking immediate clarity on which botanical formulas best support their current physical state.",
    dosage: "30-minute virtual audit with $20 credit",
    scentNotes: "Focused botanical guidance",
    certifications: ['100% Handcrafted', 'All-Natural Botanicals', 'Ethically Sourced', 'Non-GMO'],
    tags: ["Consultations & Rituals", "Clarity", 'Organic', 'Handcrafted', 'Haus of Zen']
  },
  {
    id: "GYQWHHZVFICVETM2T3BVEDUA",
    squareCatalogItemId: "GYQWHHZVFICVETM2T3BVEDUA",
    squareVariationId: "ABB75MCSK6CDYEH5OIXF4WKA",
    name: "The Deep Dive",
    botanicalName: "Master Clinical Protocol",
    subtitle: "Comprehensive 1-on-1 Hormonal & Lifestyle Herbal Review",
    description: "A comprehensive, one on one consultation exploring your hormonal patterns, lifestyle rhythms, and nutritional needs to create a truly personalized herbal approach.\nIn depth health and lifestyle review\nCustom herbal protocol delivered as a PDF\n10 percent off apothecary purchase",
    price: 120.00,
    compareAtPrice: 138.00,
    category: "Consultations & Rituals",
    intent: "Balance",
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/5153dd84693a4698719f6bc71e20ea1133fcbb96/original.jpeg",
    gallery: ["https://items-images-production.s3.us-west-2.amazonaws.com/files/5153dd84693a4698719f6bc71e20ea1133fcbb96/original.jpeg"],
    volume: "Full Consultation + Protocol PDF",
    sizeOptions: undefined,
    inStock: true,
    featured: false,
    rating: 4.92,
    reviewCount: 70,
    ingredients: ["In-Depth Health Review", "Custom PDF Herbal Protocol", "10% Off All Apothecary Purchases"],
    ritualGuide: "Our most comprehensive wellness consultation covering full pelvic mapping, stress physiology, and bespoke formulation.",
    dosage: "Comprehensive clinical session + written protocol",
    scentNotes: "Empowered sacred wellness",
    certifications: ['100% Handcrafted', 'All-Natural Botanicals', 'Ethically Sourced', 'Non-GMO'],
    tags: ["Consultations & Rituals", "Balance", 'Organic', 'Handcrafted', 'Haus of Zen', 'The Deep Dive']
  }
];
